cd vizualy-assistant
npm publish
cd ../vizualy-area-chart
npm publish
cd ../vizualy-stacked-area-chart
npm publish
cd ../vizualy-bar-chart
npm publish
cd ../vizualy-bubble-chart
npm publish
cd ../vizualy-circle-packing-chart
npm publish
cd ../vizualy-horizontal-bullet-chart
npm publish
cd ../vizualy-horizontal-grouped-bar-chart
npm publish
cd ../vizualy-horizontal-stacked-bar-chart
npm publish
cd ../vizualy-line-bar-chart
npm publish
cd ../vizualy-line-chart
npm publish
cd ../vizualy-network-chart
npm publish
cd ../vizualy-pie-chart
npm publish
cd ../vizualy-radial-chart
npm publish
cd ../vizualy-sunburst-chart
npm publish
cd ../vizualy-vertical-grouped-bar-chart
npm publish
cd ../vizualy-vertical-stacked-bar-chart
npm publish
cd ../vizualy
npm publish
cd ..